name: "team_sort"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    environment:
      REDIS_URL: redis://redis:6379
      REDIS_SIDEKIQ_DB: 1

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium
    - redis
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/var/lib/redis/data
  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

volumes:
  redis-data: null

  
